//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.04.05 at 12:28:00 PM NZST
//


import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SPKECORESPRODUCTCATEGORYENTITY" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ACTIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CATEGORYDESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CATEGORYKEYWORDS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CREATEDDATEANDTIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="DEFAULTPROJECTGLOBALCATEGORYID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ENTERPRISE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FRIENDLYCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ISTANGIBLEPRODUCT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LEVEL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="MODIFIEDDATEANDTIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="PARENTPRODUCTCATEGORYCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PARENTPRODUCTCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PRODUCTCATEGORYHIERARCHYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PROJECTCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RECORDID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spkecoresproductcategoryentity"
})
@XmlRootElement(name = "Document")
public class ProductCategoryResponse {

    @XmlElement(name = "SPKECORESPRODUCTCATEGORYENTITY")
    protected List<SPKECORESPRODUCTCATEGORYENTITY> spkecoresproductcategoryentity;

    /**
     * Gets the value of the spkecoresproductcategoryentity property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spkecoresproductcategoryentity property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPKECORESPRODUCTCATEGORYENTITY().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPKECORESPRODUCTCATEGORYENTITY }
     *
     *
     */
    public List<SPKECORESPRODUCTCATEGORYENTITY> getSPKECORESPRODUCTCATEGORYENTITY() {
        if (spkecoresproductcategoryentity == null) {
            spkecoresproductcategoryentity = new ArrayList<SPKECORESPRODUCTCATEGORYENTITY>();
        }
        return this.spkecoresproductcategoryentity;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ACTIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CATEGORYDESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CATEGORYKEYWORDS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CREATEDDATEANDTIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="DEFAULTPROJECTGLOBALCATEGORYID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ENTERPRISE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FRIENDLYCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ISTANGIBLEPRODUCT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LEVEL" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="MODIFIEDDATEANDTIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="PARENTPRODUCTCATEGORYCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PARENTPRODUCTCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PRODUCTCATEGORYHIERARCHYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PROJECTCATEGORYNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RECORDID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "active",
        "categorydescription",
        "categorykeywords",
        "code",
        "createddateandtime",
        "defaultprojectglobalcategoryid",
        "enterprise",
        "friendlycategoryname",
        "iscategoryinheritingparentcategoryattributes",
        "iscategoryinheritingparentproductattributes",
        "istangibleproduct",
        "level",
        "modifieddateandtime",
        "parentproductcategorycode",
        "parentproductcategoryname",
        "productcategoryhierarchyname",
        "projectcategoryname",
        "recordid"
    })
    public static class SPKECORESPRODUCTCATEGORYENTITY {

        @XmlElement(name = "NAME", required = true)
        protected String name;
        @XmlElement(name = "ACTIVE", required = true)
        protected String active;
        @XmlElement(name = "CATEGORYDESCRIPTION", required = true)
        protected String categorydescription;
        @XmlElement(name = "CATEGORYKEYWORDS", required = true)
        protected String categorykeywords;
        @XmlElement(name = "CODE", required = true)
        protected String code;
        @XmlElement(name = "CREATEDDATEANDTIME", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createddateandtime;
        @XmlElement(name = "DEFAULTPROJECTGLOBALCATEGORYID", required = true)
        protected String defaultprojectglobalcategoryid;
        @XmlElement(name = "ENTERPRISE", required = true)
        protected String enterprise;
        @XmlElement(name = "FRIENDLYCATEGORYNAME", required = true)
        protected String friendlycategoryname;
        @XmlElement(name = "ISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES", required = true)
        protected String iscategoryinheritingparentcategoryattributes;
        @XmlElement(name = "ISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES", required = true)
        protected String iscategoryinheritingparentproductattributes;
        @XmlElement(name = "ISTANGIBLEPRODUCT", required = true)
        protected String istangibleproduct;
        @XmlElement(name = "LEVEL")
        protected String level;
        @XmlElement(name = "MODIFIEDDATEANDTIME", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar modifieddateandtime;
        @XmlElement(name = "PARENTPRODUCTCATEGORYCODE", required = true)
        protected String parentproductcategorycode;
        @XmlElement(name = "PARENTPRODUCTCATEGORYNAME", required = true)
        protected String parentproductcategoryname;
        @XmlElement(name = "PRODUCTCATEGORYHIERARCHYNAME", required = true)
        protected String productcategoryhierarchyname;
        @XmlElement(name = "PROJECTCATEGORYNAME", required = true)
        protected String projectcategoryname;
        @XmlElement(name = "RECORDID", required = true)
        protected String recordid;

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNAME() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNAME(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the active property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getACTIVE() {
            return active;
        }

        /**
         * Sets the value of the active property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setACTIVE(String value) {
            this.active = value;
        }

        /**
         * Gets the value of the categorydescription property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCATEGORYDESCRIPTION() {
            return categorydescription;
        }

        /**
         * Sets the value of the categorydescription property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCATEGORYDESCRIPTION(String value) {
            this.categorydescription = value;
        }

        /**
         * Gets the value of the categorykeywords property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCATEGORYKEYWORDS() {
            return categorykeywords;
        }

        /**
         * Sets the value of the categorykeywords property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCATEGORYKEYWORDS(String value) {
            this.categorykeywords = value;
        }

        /**
         * Gets the value of the code property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCODE() {
            return code;
        }

        /**
         * Sets the value of the code property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCODE(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the createddateandtime property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getCREATEDDATEANDTIME() {
            return createddateandtime;
        }

        /**
         * Sets the value of the createddateandtime property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setCREATEDDATEANDTIME(XMLGregorianCalendar value) {
            this.createddateandtime = value;
        }

        /**
         * Gets the value of the defaultprojectglobalcategoryid property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDEFAULTPROJECTGLOBALCATEGORYID() {
            return defaultprojectglobalcategoryid;
        }

        /**
         * Sets the value of the defaultprojectglobalcategoryid property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDEFAULTPROJECTGLOBALCATEGORYID(String value) {
            this.defaultprojectglobalcategoryid = value;
        }

        /**
         * Gets the value of the enterprise property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getENTERPRISE() {
            return enterprise;
        }

        /**
         * Sets the value of the enterprise property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setENTERPRISE(String value) {
            this.enterprise = value;
        }

        /**
         * Gets the value of the friendlycategoryname property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFRIENDLYCATEGORYNAME() {
            return friendlycategoryname;
        }

        /**
         * Sets the value of the friendlycategoryname property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFRIENDLYCATEGORYNAME(String value) {
            this.friendlycategoryname = value;
        }

        /**
         * Gets the value of the iscategoryinheritingparentcategoryattributes property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES() {
            return iscategoryinheritingparentcategoryattributes;
        }

        /**
         * Sets the value of the iscategoryinheritingparentcategoryattributes property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setISCATEGORYINHERITINGPARENTCATEGORYATTRIBUTES(String value) {
            this.iscategoryinheritingparentcategoryattributes = value;
        }

        /**
         * Gets the value of the iscategoryinheritingparentproductattributes property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES() {
            return iscategoryinheritingparentproductattributes;
        }

        /**
         * Sets the value of the iscategoryinheritingparentproductattributes property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setISCATEGORYINHERITINGPARENTPRODUCTATTRIBUTES(String value) {
            this.iscategoryinheritingparentproductattributes = value;
        }

        /**
         * Gets the value of the istangibleproduct property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getISTANGIBLEPRODUCT() {
            return istangibleproduct;
        }

        /**
         * Sets the value of the istangibleproduct property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setISTANGIBLEPRODUCT(String value) {
            this.istangibleproduct = value;
        }

        /**
         * Gets the value of the level property.
         *
         */
        public String getLEVEL() {
            return level;
        }

        /**
         * Sets the value of the level property.
         *
         */
        public void setLEVEL(String value) {
            this.level = value;
        }

        /**
         * Gets the value of the modifieddateandtime property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getMODIFIEDDATEANDTIME() {
            return modifieddateandtime;
        }

        /**
         * Sets the value of the modifieddateandtime property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setMODIFIEDDATEANDTIME(XMLGregorianCalendar value) {
            this.modifieddateandtime = value;
        }

        /**
         * Gets the value of the parentproductcategorycode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPARENTPRODUCTCATEGORYCODE() {
            return parentproductcategorycode;
        }

        /**
         * Sets the value of the parentproductcategorycode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPARENTPRODUCTCATEGORYCODE(String value) {
            this.parentproductcategorycode = value;
        }

        /**
         * Gets the value of the parentproductcategoryname property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPARENTPRODUCTCATEGORYNAME() {
            return parentproductcategoryname;
        }

        /**
         * Sets the value of the parentproductcategoryname property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPARENTPRODUCTCATEGORYNAME(String value) {
            this.parentproductcategoryname = value;
        }

        /**
         * Gets the value of the productcategoryhierarchyname property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPRODUCTCATEGORYHIERARCHYNAME() {
            return productcategoryhierarchyname;
        }

        /**
         * Sets the value of the productcategoryhierarchyname property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPRODUCTCATEGORYHIERARCHYNAME(String value) {
            this.productcategoryhierarchyname = value;
        }

        /**
         * Gets the value of the projectcategoryname property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPROJECTCATEGORYNAME() {
            return projectcategoryname;
        }

        /**
         * Sets the value of the projectcategoryname property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPROJECTCATEGORYNAME(String value) {
            this.projectcategoryname = value;
        }

        /**
         * Gets the value of the recordid property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRECORDID() {
            return recordid;
        }

        /**
         * Sets the value of the recordid property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRECORDID(String value) {
            this.recordid = value;
        }

    }

}
